marie-szz/nosweat

app/controllers/products_controller.rb, app/models/product.rb, app/models/user.rb, app/views/products/index.html.erb, app/views/products/show.html.erb, config/routes.rb, db/migrate/20220221161244_create_products.rb, db/schema.rb, test/controllers/products_controller_test.rb, test/models/product_test.rb
Product MVC (views to be updated)
=> MVC product

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/new.html.erb, app/views/products/show.html.erb, config/routes.rb, db/migrate/20220221161823_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb
creating routes for products and bookings + creating booking mvc
=> Routes and booking mvc

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/products_controller.rb, app/policies/application_policy.rb, app/policies/product_policy.rb, app/views/products/_form.html.erb, app/views/products/index.html.erb, app/views/products/new.html.erb, config/routes.rb, test/policies/product_policy_test.rb
Added pundit for methods new and create for product
=> pundit + methods new and create for product with form

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_main-search-bar.scss, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> modification de la navbar

.gitignore, Gemfile, Gemfile.lock, app/models/product.rb, config/environments/development.rb, config/storage.yml, db/migrate/20220222101337_create_active_storage_tables.active_storage.rb, db/migrate/20220222112223_change_column_name_photos.rb, db/migrate/20220222143916_remove_column_to_product.rb, db/schema.rb, db/seeds.rb
=> Migration db seed w cloudinary

app/controllers/bookings_controller.rb, app/controllers/products_controller.rb, app/policies/booking_policy.rb, app/views/products/_form.html.erb, app/views/products/show.html.erb, db/migrate/20220222162730_add_checkin_and_checkout_to_bookings.rb, db/schema.rb, test/policies/booking_policy_test.rb
correction of the product form to add many pictures
booking form on the show
=> booking form and correction of product formé

app/assets/stylesheets/components/_card.scss, app/views/pages/_card.html.erb, app/views/pages/_footer.html.erb
=> Modification des cartes, pluriel + rounded images

app/assets/stylesheets/components/_navbar.scss, app/javascript/controllers/navbar_controller.js
=> navbar becomes blue after scrolling below banner

app/assets/stylesheets/components/_avatar.scss, app/views/shared/_navbar.html.erb, app/views/shared/_navbar_home.html.erb
navbar avatar and delete message and home
=> navbar avatar

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_navbar_home.html.erb
=> navbar avatar + devise en français

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_index_card.scss, app/assets/stylesheets/pages/_home.scss, app/views/products/index.html.erb
=> frontend index

config/environments/production.rb
=> cloudinary prod

app/controllers/bookings_controller.rb, app/controllers/products_controller.rb, app/views/products/show.html.erb
=> modif parcours

app/assets/stylesheets/components/_card.scss, app/views/pages/_card.html.erb
hover on the cards + you can click wherever on the card
=> home cards hover and link

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_index_card.scss, app/assets/stylesheets/config/_colors.scss, app/views/products/index.html.erb, app/views/products/new.html.erb
=> améliorations front index

app/views/products/index.html.erb, app/views/products/show.html.erb
=> correction form show

db/migrate/20220224093925_add_size_to_products.rb, db/migrate/20220224094139_add_status_to_bookings.rb, db/schema.rb
added size to products
added status to bookings
=> add columns to db

app/views/products/show.html.erb
=> show wip but has to be pushed so that I can pull

app/views/products/show.html.erb
=> show pushed again

Gemfile, Gemfile.lock, config/initializers/geocoder.rb, db/migrate/20220224124146_add_coordinates_to_users.rb, db/schema.rb
=> geocoding setup

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index_card.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/products_controller.rb, app/javascript/controllers/mapbox_controller.js, app/models/user.rb, app/views/products/index.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_navbar_home.html.erb, package.json, yarn.lock
adding map to index + "ajouter un produit" dans le dropdown de la navbar"
=> adding map to index

app/assets/stylesheets/components/_index_card.scss, app/assets/stylesheets/pages/_home.scss
=> resolution de bugs css

app/assets/stylesheets/components/_index_card.scss, app/javascript/controllers/mapbox_controller.js, app/views/products/index.html.erb
=> correction map et cards index

app/javascript/controllers/mapbox_controller.js, app/views/products/index.html.erb, db/seeds.rb
=> ajouts tailles

app/views/products/index.html.erb
=> api fixing bug

app/assets/config/manifest.js
=> résolution error JS

app/assets/stylesheets/components/_card.scss, app/views/products/show.html.erb
=> modif front show product

app/views/products/show.html.erb
=> show-articles-same-user

app/controllers/products_controller.rb, app/models/product.rb, app/views/products/index.html.erb, app/views/shared/_search_bar.html.erb, package.json, yarn.lock
search-bar address filter and quality and size
=> search-bar-address-quality-size

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/dashboard.js, app/views/pages/dashboard.html.erb, app/views/products/show.html.erb
=> dashboard js

app/javascript/packs/application.js
=> Javascript

app/views/products/show.html.erb
=> show modal

app/views/pages/dashboard.html.erb
=> dashboard design

app/assets/stylesheets/components/_card.scss, app/views/products/show.html.erb
=> ajout du link_to sur les mini cards

db/seeds.rb
=> nouvelle seed

app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb
=> Dashboard back end

app/views/pages/dashboard.html.erb
=> add notif sur le dashboard

app/views/products/show.html.erb
=> show other articles not dupplicated

app/views/products/show.html.erb
=> debugging show

app/views/pages/dashboard.html.erb
=> in line items
